5mHeightLimit
bump
closedToAll
deadEnd
keepLeft
keepLeftRight
leftTurnOnly
noEntry
noLeftTurn
noMotorVehicles
noParking
noRightTurn
noStopping
oneway
pedestrianCrossing
pedestrianCrossingR
rightOnly
rightTurnOnly
stop
yield
